language: python
env:
  global:
  - PROJECT_NAME=hicreppy
  - GITHUB_REPO_NAME=cmdoret/hicreppy
matrix:
  include:
  - python: '3.6'
  - python: '3.7'
    dist: xenial
    sudo: true
os:
- linux
install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- source "$HOME/miniconda/etc/profile.d/conda.sh"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda config --add channels bioconda
- conda update -q conda
- conda info -a
- conda create -c conda-forge -q -n test-environment python="$TRAVIS_PYTHON_VERSION" pytest  pytest-cov  pylint codecov  cooler pylint
- conda activate test-environment
- pip install -Ur requirements.txt
- pip install pytest-pylint
script:
- pytest --pylint --pylint-error-types=EF --pylint-rcfile=.pylintrc --cov=hicreppy # Run tests, linting and make coverage report
after_success:
- codecov
deploy:
  on:
    branch: master
    tags: true
  provider: pypi
  skip_existing: true
  user: cmdoret
  password:
    secure: lL8sSIW6BXepJiCyZco5BgIUr9R5fXzXPwt3/imiaTwX/tijYj3b8qAyusc5ExPP1bzJ7pQWFDW4mBSXPQLL4nfuIfu47iU03CFVAXGr/IHty9rRU3l6/T6gh2o2TYnWZMU/lcOKtwT+Zd2T3g4DTfh1Y9VcBooHikSWB5nOuXOSt3bzE2gkKlkDoA5GZhN2u/GKapnLOkvc9UfuGBSEkP7t88CJA5SDSuWuBAv2wEYrHO7ofNztqr5qxlbreSpn3+B6WiRaPtHVzwkLVZsL3OJ0Fr/MtpTaAQskL6opO/7aIM0Y/HoLenwUwomol6omWVGopuHEHI0Iq/FcoSmcWwccgnlZLhjcc1V3yWBAmPb39xiui6whvsRkbF6YDyDCFBiAIPY02s7xo/qpXj8hNfv1PrPGkuYrXCdydBIJs0Ihjdy3y7uWVCbPAxIpTggsR0yXJxmKEKvZNz30YbxQNC3QLqaWoxA5m8CPT1hU43J1FaXVo8ncnAiAga8fcec9ZwFhbMDyoarKCcprEPWg0EER/m/1iykb5UrHS7foLDJKNYw6YXrcNvniPvmdfkerxKIMzHik7WNlmFrKEtHA4+mCrr+nyN842lMzk+OMNhra6IF2koCRq3F0NNe7ryEp3hkCOYEM3AKEfthMsCrvVJ40lnLyrLD6qKXQQ+YvhQc=
  distributions: sdist bdist_wheel
